version: 1.1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    cd src

    nuget restore

    cd ..
build:
  publish_nuget: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  server: https://www.myget.org/F/yaclp/api/v2/package
  api_key:
    secure: shfnDtqvaNhaz7EQolekac0LkvNhqqi31VtWgTA2+JYktOxHuiI3Xsgwr+kFKWzM
  symbol_server: https://www.myget.org/F/yaclp/symbols/api/v2/package
  on:
    branch: master
