version: "3"

services:

  yaclp:
    image: yaclp
    build:
      context: .
      dockerfile: Dockerfiles/yaclp.Dockerfile
      args:
        BUILD_NUMBER: $BUILD_NUMBER

  yaclp-tests:
    image: yaclp-tests
    build:
      context: .
      dockerfile: Dockerfiles/yaclp-tests.Dockerfile
